### ISSUE TITLE
Base branch is fixed to `main`

### ISSUE THREAD

**Issue by tristanlee85** [romoh/dependencies-autoupdate#6]
> Pull request defaults to the branch checked out in the workflow.

This statement appears invalid. From the source, I see that it is fixed to `main` branch which may not exist on legacy repos where the default used to be `master`.

**Comment by emZubair** [comment]
@tristanlee85 I've opened a [PR-8](https://github.com/romoh/dependencies-autoupdate/pull/8) which adds the support for a custom branch 
In the meantime you can use the following action [available on the marketplace](https://github.com/marketplace/actions/dependencies-autoupdate-with-custom-branch) which is fork of this repo and supports custom branch.

**Comment by romoh** [comment]
Addressed by #8
